Aceitar tipos customizados de serviços
Deividy/frete pull request #8
Opened 2021-12-20 21:02 UTC by luizspinelli

Aceitar tipos customizados de serviços oferecidos pelos correios a empresas parceiras

2021-12-28 01:49 UTC, Deividy requested changes

2021-12-28 01:49 UTC, Deividy commented on frete.d.ts
> +         [key: string]: string;
What are these types? Can we map them? Looks like Correios now has an [API to list services](http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=ListaServicos), can we use this to get these services and map them?

2021-12-28 01:51 UTC, Deividy commented
Thanks for your submission! :) 

But, this PR is only adding TypeScript declaration, the best we can do is map the services (if is possible), if it is not possible to map the services (e.g. correios accepts random service codes),  we might need some tweaks [here](https://github.com/Deividy/frete/blob/master/frete.js#L314) and a unit test for this.

2021-12-29 19:01 UTC, EduardoJM requested changes
Taking from the Correios API (@Deividy commented in this PR), we get a service list:

https://pastebin.com/raw/vbWVqTEP


I can only comment in the edited parts and, now, here is a better solution to allow custom services and not lose the type inference from TypeScript:

```ts
export interface FreteOptions {
    //...
    servico: string;
    nCdServico: string;
    // ...

// ...

export interface Frete extends FretePropertiesPrototype {
    servico(value: CodigosServico): Frete;
    servico(value: string): Frete;
    // ...

// ...
```

Now we have (in TypeScript) two overloads of the function, one accepts only the declared types and the other accepts any string value.

Using this solution is needed to think about https://github.com/Deividy/frete/blob/master/frete.js#L314 (commented by @Deividy).

The idea of accept custom services is: if Correios add a new service is fastest add a custom service than making a PR or other thing. Then, is possible to make a mapping of all services above (taken from the API) and add this support for custom service code.

what do you think about it @Deividy?

2021-12-29 19:01 UTC, EduardoJM commented on frete.d.ts
> +         [key: string]: string;
The `[key: string]: string` indicate that a object implementating (or with those interface type) aceppts any string key with a string value as object member.

One important thing about this change is: that is not the best way to insert custom service types (type inference problems). For example, using the original declaration, when we need to add a variable with type **CodigosServico**, we have a good type inference and error checking:
![image](https://user-images.githubusercontent.com/20397491/147692403-3e147613-edaa-4787-922f-ca39e12e2480.png)

But, without it, we not have autocomplete or type checking (because the CodigosServico accepts any string):
![image](https://user-images.githubusercontent.com/20397491/147692476-732f6577-3833-486d-8d6b-e58e66466872.png)
*no error red underline here*

2021-12-29 19:18 UTC, EduardoJM commented
> 
> Now we have (in TypeScript) two overloads of the function, one accepts only the declared types and the other accepts any string value.
>

Is that:

![Screenshot from 2021-12-29 15-56-27](https://user-images.githubusercontent.com/20397491/147696093-c3e49317-1a18-477b-94ed-35d33c5291fc.png)

![Screenshot from 2021-12-29 15-56-39](https://user-images.githubusercontent.com/20397491/147696101-ebc39745-8f2d-4727-8f23-017bf9c5f594.png)

![Screenshot from 2021-12-29 15-56-19](https://user-images.githubusercontent.com/20397491/147696126-0d6c2814-7f06-4d9e-a886-5a9c46c16f02.png)

Working (compiling TS to JS and running with node) in the two usage scenario (using mapped services and using custom):

![Screenshot from 2021-12-29 15-56-07](https://user-images.githubusercontent.com/20397491/147696147-c9eeca80-636d-40cd-9097-3b8d9117697e.png)

![Screenshot from 2021-12-29 15-55-44](https://user-images.githubusercontent.com/20397491/147696189-78963149-099c-4fe5-a9f6-61ea7dbf84bb.png)

2022-01-02 14:38 UTC, Deividy commented
wow, there is a lot of services nowadays, makes me think if that dictionary of `frete.servicos*` is still useful, we may want to remove this in future 🤔

2022-01-02 14:39 UTC, merged

2022-01-02 14:43 UTC, Deividy commented
thanks @EduardoJM for all the explanation/tests, makes a lot of sense...  merged this PR and added the [`listaServicos`](https://github.com/Deividy/frete/blob/master/frete.js#L234-L236) to our frete :)

also, I updated our wsdl (which was 6 years old!), please let me know if you guys have any issues with this

2022-01-02 16:38 UTC, Deividy commented
I'm sorry, reverted. I miss understood the comments (my bad :$)

anyways...

the main idea here is; 
our module should accept any arbitrary code that correios might add in the future (what it already does), having a dictionary for type checking/easy access to these codes is very handy, but not necessary

so, to improve our TypeScript, we can use the interface suggested by @EduardoJM, which I liked!
```ts
export interface FreteOptions {
    //...
    servico: string;
    nCdServico: string;
// ...
export interface Frete extends FretePropertiesPrototype {
    servico(value: CodigosServico): Frete;
    servico(value: string): Frete;
```
and maybe get the response from `listaServicos()` and load this as a utility? is not that big and might be useful to easy/fast checking codes and find services

2022-01-02 17:48 UTC, Deividy commented
Well.. since I caused some confusion here (merging/reverting), I decided to jump in with you guys! :)

I made some things;
- First, dumped the response of `listaServicos` to [`dumps/listaServicos.json`](https://github.com/Deividy/frete/blob/master/dumps/listaServicos.json), also moved the `
CalcPrecoPrazo.xml` to the same path
 
- Added a script ([`dump-services.js`](https://github.com/Deividy/frete/blob/master/dump-services.js)) that knows how to query correios and save the `listaServicos.json`, which is small (40.2kb and 332 services), also this script knows (in a very hacky way) how to read the [`frete.d.ts`](https://github.com/Deividy/frete/blob/master/frete.d.ts#L3-L340) and update the definition :)

- And finally, I added a way to get these services in our `frete.js`, now we have a [`frete.servicos.list`](https://github.com/Deividy/frete/blob/master/frete.js#L55) (with all services), and the `frete.servicos.names{}` with all names, bonus that we have a [`frete.servicos.search()`](https://github.com/Deividy/frete/blob/master/frete.spec.js#L433-L451) to search services

the only drawback of this approach is that we now ship all these services with our module and we have to maintain the `listaServicos.json`, since it's small and it's all very handy, think it's fair enough. 

what do you guys think?